# Generated by Django 3.0.8 on 2020-09-18 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_purchased_item_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchased_item',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.ShippingAddress'),
        ),
    ]
